ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

frontend:
  image:
    repository: aaryan8/three-tier-frontend
    tag: v1

backend:
  image:
    repository: aaryan8/three-tier-backend
    tag: v1

