{{- if .Values.rbac.createServiceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "threeTier.fullname" . }}-frontend
  labels:
    {{- include "threeTier.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.rbac.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "threeTier.fullname" . }}-backend
  labels:
    {{- include "threeTier.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.rbac.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "threeTier.fullname" . }}-postgres
  labels:
    {{- include "threeTier.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.rbac.automountServiceAccountToken }}
{{- end }}
